tensorboard:
  _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  save_dir: ${save_dir}
  name: ${name}
  version: ${run_id}
  log_graph: False
  default_hp_metric: False
  prefix: ""
