_target_: pytorch_lightning.Trainer

min_epochs: 1
max_epochs: ${epochs}

accelerator: "auto"  # automatically set gpu or cpu
# devices are specified on instantiation
strategy: null  # or "ddp"

log_every_n_steps: 1
gradient_clip_val: 0.1

# number of validation steps to execute at the beginning of the training
num_sanity_val_steps: 0
